import { Skill } from "../../../shared/types/pal";

export const BUILTIN_SKILLS: Skill[] = [
  {
    id: "builtin_codereview",
    name: "Code Review",
    category: "PAL",
    description: "Review this code for issues, best practices and improvements.",
    builtinPalTool: "codereview",
    template: "Review this code for issues, best practices and improvements:\n\n{{code}}",
    variables: [{ name: "code", type: "string", required: true, description: "Code to review" }],
    isBuiltin: true,
    schemaVersion: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "builtin_plan",
    name: "Plan Feature",
    category: "PAL",
    description: "Create a detailed implementation plan.",
    builtinPalTool: "planner",
    template: "Create a detailed implementation plan for:\n\n{{feature}}\n\nContext: {{context}}",
    variables: [
      { name: "feature", type: "string", required: true },
      { name: "context", type: "string", required: false, default: "No additional context" },
    ],
    isBuiltin: true,
    schemaVersion: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "builtin_debug",
    name: "Debug Issue",
    category: "PAL",
    description: "Debug this issue.",
    builtinPalTool: "debug",
    template: "Debug this issue:\n\n{{error}}\n\nRelevant code:\n{{code}}",
    variables: [
      { name: "error", type: "string", required: true },
      { name: "code", type: "string", required: false, default: "" },
    ],
    isBuiltin: true,
    schemaVersion: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "builtin_thinkdeep",
    name: "Think Deep",
    category: "PAL",
    description: "Analyze deeply.",
    builtinPalTool: "thinkdeep",
    template: "Analyze deeply:\n\n{{topic}}",
    variables: [{ name: "topic", type: "string", required: true }],
    isBuiltin: true,
    schemaVersion: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: "builtin_consensus",
    name: "Consensus Check",
    category: "PAL",
    description: "Get consensus on this decision.",
    builtinPalTool: "consensus",
    template: "Get consensus on this decision:\n\n{{decision}}\n\nOptions:\n{{options}}",
    variables: [
      { name: "decision", type: "string", required: true },
      { name: "options", type: "string", required: false, default: "" },
    ],
    isBuiltin: true,
    schemaVersion: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
